services:
  - type: worker
    name: Zarabotok49_bot
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: SUPPORT_USERNAME
        value: lotus762001
      - key: SHOP_TITLE
        value: Заработок на нейросетях
      - key: START_TEXT
        value: Добро пожаловать в магазин по заработку на нейросетях! Здесь вы можете купить гайды, промпты и инструменты, которые помогут начать зарабатывать с помощью ИИ уже сегодня.
      - key: SHOP_TEXT
        value: Выберите цифровой продукт ниже и оплатите его звездами Telegram.
      - key: PRODUCTS_JSON
        value: >-
          [{"code":"product_1","title":"1000 ПРОМПТОВ ДЛЯ ЗАРАБОТКА С CHATGPT","description":"Руководство «1000 промптов для заработка с ChatGPT» — это готовые запросы, которые помогут зарабатывать на текстах, контенте, маркетинге, переводах, идеях и онлайн-услугах с помощью нейросетей даже без опыта","price_stars":200,"delivery_text":"Спасибо за покупку!\nВаш цифровой продукт готов к скачиванию:\nСсылка: https://clck.ru/3SnYDx\nСохраните файл себе на устройство\nЕсли возникнут вопросы, напишите в поддержку: @lotus762001"},{"code":"product_2","title":"50 СПОСОБОВ ЗАРАБОТАТЬ НА НЕЙРОСЕТЯХ В 2026 ГОДУ","description":"«50 способов заработать на нейросетях в 2026 году» — сборник актуальных идей и пошаговых схем заработка с помощью искусственного интеллекта.","price_stars":210,"delivery_text":"Спасибо за покупку!\nВаш цифровой продукт готов к скачиванию:\nСсылка: https://clck.ru/3SnYqW\nСохраните файл себе на устройство\nЕсли возникнут вопросы, напишите в поддержку: @lotus762001"},{"code":"product_3","title":"365 ИДЕЙ КОНТЕНТА ДЛЯ TELEGRAM / TIKTOK / REELS","description":"«365 идей контента для Telegram, TikTok и Reels» — это готовый план постов и видео на каждый день, который поможет регулярно публиковать контент, набирать подписчиков и зарабатывать","price_stars":190,"delivery_text":"Спасибо за покупку!\nВаш цифровой продукт готов к скачиванию:\nСсылка: https://clck.ru/3SnZUN\nСохраните файл себе на устройство\nЕсли возникнут вопросы, напишите в поддержку: @lotus762001"},{"code":"product_4","title":"КАК ДЕЛАТЬ AI-ВИДЕО И ЗАРАБАТЫВАТЬ НА НИХ","description":"Руководство «Как делать AI-видео и зарабатывать на них» — это пошаговая инструкция по созданию видео с помощью нейросетей и способам заработка на коротких видео и контенте","price_stars":208,"delivery_text":"Спасибо за покупку!\nВаш цифровой продукт готов к скачиванию:\nСсылка: https://clck.ru/3SnZgq\nСохраните файл себе на устройство\nЕсли возникнут вопросы, напишите в поддержку: @lotus762001"}]
